[package]
name = "fileqry"
version = "0.0.0"
authors = ["Erik Zscheile <zseri.devel@ytrizja.de>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4"
notify = "5.0.0-pre.2"
salsa = "0.14"
path-clean = "0.1.0"
